[global]
error_log = /var/www/storage/logs/php-fpm/php-fpm.log

[www]
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
pm.max_requests = 200

access.log = /var/www/storage/logs/php-fpm/$pool.access.log
access.format = "%R - %u %t \"%m %r%Q%q\" %s %f %{milli}d ms %{kilo}M KB CPU:%C%%"
