[global]
error_log = /var/www/storage/logs/php-fpm/php-fpm.log

[www]

pm.max_children = 10
pm.start_servers = 3
pm.min_spare_servers = 2
pm.max_spare_servers = 5
pm.max_requests = 500



access.log = /var/www/storage/logs/php-fpm/$pool.access.log
access.format = "%R - %u %t \"%m %r%Q%q\" %s %f %{milli}d ms %{kilo}M KB CPU:%C%%"
